export const IconNames = {
  Activity: "Activity",
  Airplay: "Airplay",
  AlertCircle: "Alert Circle",
  AArowDown: "Arrow Down",
  AArowUp: "Arrow Up",
  ALargeSmall: "Large Small",
  Accesibility: "Accessibility",
  AirVent: "Air Vent",
  AlarmClock: "Alarm Clock",
  AlarmClockCheck: "Alarm Clock Check",
  AlarmClockMinus: "Alarm Clock Minus",
  AlarmClockOff: "Alarm Clock Off",
  AlarmClockPlus: "Alarm Clock Plus",
  AlignCenter: "Align Center",
  AlignCenterHorizontal: "Align Center Horizontal",
  AlignCenterVertical: "Align Center Vertical",
  AlignEndHorizontal: "Align End Horizontal",
  AlignEndVertical: "Align End Vertical",
  AlignHorizontalDistributeCenter: "Align Horizontal Distribute Center",
  AlignHorizontalDistributeEnd: "Align Horizontal Distribute End",
  AlignHorizontalDistributeStart: "Align Horizontal Distribute Start",
  AlignHorizontalJustifyCenter: "Align Horizontal Justify Center",
  AlignHorizontalJustifyEnd: "Align Horizontal Justify End",
  AlignHorizontalJustifyStart: "Align Horizontal Justify Start",
  AlignHorizontalSpaceAround: "Align Horizontal Space Around",
  AlignHorizontalSpaceBetween: "Align Horizontal Space Between",
  AlignJustify: "Align Justify",
  AlignLeft: "Align Left",
  AlignRight: "Align Right",
  AlignStartHorizontal: "Align Start Horizontal",
  AlignStartVertical: "Align Start Vertical",
  AlignVerticalDistributeCenter: "Align Vertical Distribute Center",
  AlignVerticalDistributeEnd: "Align Vertical Distribute End",
  AlignVerticalDistributeStart: "Align Vertical Distribute Start",
  AlignVerticalSpaceBetween: "Align Vertical Space Between",
  AlignVerticalJustifyCenter: "Align Vertical Justify Center",
  AlignVerticalJustifyEnd: "Align Vertical Justify End",
  AlignVerticalJustifyStart: "Align Vertical Justify Start",
  AlignVerticalSpaceAround: "Align Vertical Space Around",
  CornerDownLeft: "Corner Down Left",
  CornerDownRight: "Corner Down Right",
  CornerLeftDown: "Corner Left Down",
  CornerLeftUp: "Corner Left Up",
  CornerRightDown: "Corner Right Down",
  CornerRightUp: "Corner Right Up",
  CornerUpLeft: "Corner Up Left",
  CornerUpRight: "Corner Up Right",
  IterationCcw: "Iteration CCW",
  IterationCw: "Iteration CW",
  LogIn: "Log In",
  LogOut: "Log Out",
  MoveDiagonal: "Move Diagonal",
  MoveDiagonal2: "Move Diagonal 2",
  MoveDown: "Move Down",
  MoveDownLeft: "Move Down Left",
  MoveDownRight: "Move Down Right",
  MoveHorizontal: "Move Horizontal",
  MoveLeft: "Move Left",
  MoveRight: "Move Right",
  MoveUp: "Move Up",
  MoveUpLeft: "Move Up Left",
  MoveUpRight: "Move Up Right",
  MoveVertical: "Move Vertical",
  RotateCcw: "Rotate CCW",
  RotateCw: "Rotate CW",
  SkipBack: "Skip Back",
  SkipForward: "Skip Forward",
  StepBack: "Step Back",
  StepForward: "Step Forward",
  UnfoldHorizontal: "Unfold Horizontal",
  UnfoldVertical: "Unfold Vertical",
  ArrowBigDown: "Arrow Big Down",
  ArrowBigDownDash: "Arrow Big Down Dash",
  ArrowBigLeft: "Arrow Big Left",
  ArrowBigLeftDash: "Arrow Big Left Dash",
  ArrowBigRight: "Arrow Big Right",
  ArrowBigRightDash: "Arrow Big Right Dash",
  ArrowBigUp: "Arrow Big Up",
  ArrowBigUpDash: "Arrow Big Up Dash",
  ArrowDown: "Arrow Down",
  ArrowDown01: "Arrow Down 0 1",
  ArrowDown10: "Arrow Down 1 0",
  ArrowDownAZ: "Arrow Down A-Z",
  ArrowDownFromLine: "Arrow Down From Line",
  ArrowDownLeft: "Arrow Down Left",
  ArrowDownNarrowWide: "Arrow Down Narrow Wide",
  ArrowDownWideNarrow: "Arrow Down Wide Narrow",
  ArrowDownRight: "Arrow Down Right",
  ArrowDownToDot: "Arrow Down To Dot",
  ArrowDownToLine: "Arrow Down To Line",
  ArrowDownUp: "Arrow Down Up",
  ArrowDownZA: "Arrow Down Z-A",
  ArrowLeft: "Arrow Left",
  ArrowLeftFromLine: "Arrow Left From Line",
  ArrowLeftRight: "Arrow Left Right",
  ArrowLeftToLine: "Arrow Left To Line",
  ArrowRight: "Arrow Right",
  ArrowRightFromLine: "Arrow Right From Line",
  ArrowRightLeft: "Arrow Right Left",
  ArrowRightToLine: "Arrow Right To Line",
  ArrowUp: "Arrow Up",
  ArrowUp01: "Arrow Up 0 1",
  ArrowUp10: "Arrow Up 1 0",
  ArrowUpAZ: "Arrow Up A-Z",
  ArrowUpDown: "Arrow Up Down",
  ArrowUpFromDot: "Arrow Up From Dot",
  ArrowUpFromLine: "Arrow Up From Line",
  ArrowUpLeft: "Arrow Up Left",
  ArrowUpNarrowWide: "Arrow Up Narrow Wide",
  ArrowUpRight: "Arrow Up Right",
  ArrowUpToLine: "Arrow Up To Line",
  ArrowUpWideNarrow: "Arrow Up Wide Narrow",
  ArrowUpZA: "Arrow Up Z-A",
  ArrowsUpFromLine: "Arrows Up From Line",
  Maximize2: "Maximize 2",
  Minimize2: "Minimize 2",
  Move: "Move",
  RefreshCcw: "Refresh CCW",
  RefreshCcwDot: "Refresh CCW Dot",
  RefreshCw: "Refresh CW",
  RefreshCwOff: "Refresh CW Off",
  Repeat: "Repeat",
  Repeat2: "Repeat 2",
  TrendingUpDown: "Trending Up Down",
  CircleArrowDown: "Circle Arrow Down",
  CircleArrowLeft: "Circle Arrow Left",
  CircleArrowRight: "Circle Arrow Right",
  CircleArrowUp: "Circle Arrow Up",
  CircleArrowOutDownLeft: "Circle Arrow Out Down Left",
  CircleArrowOutDownRight: "Circle Arrow Out Down Right",
  CircleArrowOutUpLeft: "Circle Arrow Out Up Left",
  CircleArrowOutUpRight: "Circle Arrow Out Up Right",
  SquareArrowDown: "Square Arrow Down",
  SquareArrowDownLeft: "Square Arrow Down Left",
  SquareArrawDownRight: "Square Arrow Down Right",
  SquareArrowLeft: "Square Arrow Left",
  SquareArrowRight: "Square Arrow Right",
  SquareArrowUp: "Square Arrow Up",
  SquareArrowUpLeft: "Square Arrow Up Left",
  SquareArrowUpRight: "Square Arrow Up Right",
  ChartArea: "Chart Area",
  ChartBar: "Chart Bar",
  ChartBarDecreasing: "Chart Bar Decreasing",
  ChartBarIncreasing: "Chart Bar Increasing",
  ChartBarBig: "Chart Bar Big",
  ChartBarStacked: "Chart Bar Stacked",
  ChartCandlestick: "Chart Candlestick",
  ChartColumn: "Chart Column",
  ChartColumnBig: "Chart Column Big",
  ChartColumnDecreasing: "Chart Column Decreasing",
  ChartColumnIncreasing: "Chart Column Increasing",
  ChartColumnStacked: "Chart Column Stacked",
  ChartGantt: "Chart Gantt",
  ChartLine: "Chart Line",
  ChartNetwork: "Chart Network",
  ChartNoAxesColumn: "Chart No Axes Column",
  ChartNoAxesColumnDecreasing: "Chart No Axes Column Decreasing",
  ChartNoAxesColumnIncreasing: "Chart No Axes Column Increasing",
  ChartNoAxesCombined: "Chart No Axes Combined",
  ChartNoAxesGantt: "Chart No Axes Gantt",
  ChartPie: "Chart Pie",
  ChartScatter: "Chart Scatter",
  ChartSpline: "Chart Spline",
  Kanban: "Kanban",
  SquareChartGantt: "Square Chart Gantt",
  SquareDashedKanban: "Square Dashed Kanban",
  SquareKanban: "Square Kanban",
  TrendingDown: "Trending Down",
  TrendingUp: "Trending Up",
  FolderKanban: "Folder Kanban",
  PanelsTopLeft: "Panels Top Left",
  Bitcoin: "Bitcoin",
  Chrome: "Chrome",
  Codepen: "Codepen",
  Codesandbox: "Codesandbox",
  Dribbble: "Dribbble",
  Facebook: "Facebook",
  Figma: "Figma",
  Framer: "Framer",
  Github: "Github",
  Gitlab: "Gitlab",
  Hexagon: "Hexagon",
  Instagram: "Instagram",
  Linkedin: "Linkedin",
  Pocket: "Pocket",
  Slack: "Slack",
  Target: "Target",
  Trello: "Trello",
  Twitch: "Twitch",
  Twitter: "Twitter",
  Youtube: "Youtube",
  Baby: "Baby",
  BadgeHelp: "Badge Help",
  BadgeInfo: "Badge Info",
  CircleHelp: "Circle Help",
  Contrast: "Contrast",
  EarOff: "Ear Off",
  Ear: "Ear",
  Eclipse: "Eclipse",
  EyeClosed: "Eye Closed",
  EyeOff: "Eye Off",
  Eye: "Eye",
  Glasses: "Glasses",
  Hand: "Hand",
  Info: "Info",
  LifeBuoy: "Life Buoy",
  MoonStar: "Moon Star",
  Moon: "Moon",
  PersonStanding: "Person Standing",
  ScanEye: "Scan Eye",
  ScanSearch: "Scan Search",
  Speech: "Speech",
  SunDim: "Sun Dim",
  SunMedium: "Sun Medium",
  SunMoon: "Sun Moon",
  Sun: "Sun",
  ZoomIn: "Zoom In",
  ZoomOut: "Zoom Out",
  Anvil: "Anvil",
  BrickWall: "Brick Wall",
  Building: "Building",
  Building2: "Building 2",
  Castle: "Castle",
  Church: "Church",
  Cuboid: "Cuboid",
  Dam: "Dam",
  Factory: "Factory",
  Fence: "Fence",
  GraduationCap: "Graduation Cap",
  Hospital: "Hospital",
  Hotel: "Hotel",
  Home: "Home",
  HousePlug: "House Plug",
  HousePlus: "House Plus",
  Landmark: "Landmark",
  School: "School",
  Store: "Store",
  Theater: "Theater",
  University: "University",
  UtilityPole: "Utility Pole",
  Warehouse: "Warehouse",
  CirclePlus: "Circle Plus",
  Grab: "Grab",
  Lasso: "Lasso",
  LassoSelect: "Lasso Select",
  Loader: "Loader",
  LoaderCircle: "Loader Circle",
  LoaderPinwheel: "Loader Pinwheel",
  MousePointer: "Mouse Pointer",
  MousePointer2: "Mouse Pointer 2",
  MousePointerBan: "Mouse Pointer Ban",
  MousePointerClick: "Mouse Pointer Click",
  PenTool: "Pen Tool",
  Pencil: "Pencil",
  PencilOff: "Pencil Off",
  Plus: "Plus",
  Pointer: "Pointer",
  PointerOff: "Pointer Off",
  Sparkles: "Sparkles",
  SquareDashedMousePointer: "Square Dashed Mouse Pointer",
  SquareMousePointer: "Square Mouse Pointer",
  Stamp: "Stamp",
  Text: "Text",
  TextCursor: "Text Cursor",
  TextSelect: "Text Select",
  Wand: "Wand",
  WandSparkles: "Wand Sparkles",
  AlarmSmoke: "Alarm Smoke",
  BellElectric: "Bell Electric",
  Blinds: "Blinds",
  Bolt: "Bolt",
  CookingPot: "Cooking Pot",
  DoorClosed: "Door Closed",
  DoorOpen: "Door Open",
  Drill: "Drill",
  Fan: "Fan",
  FireExtinguisher: "Fire Extinguisher",
  Hammer: "Hammer",
  Heater: "Heater",
  Microwave: "Microwave",
  PaintRoller: "Paint Roller",
  Paintbrush: "Paintbrush",
  PaintbrushVertical: "Paintbrush Vertical",
  Refrigerator: "Refrigerator",
  Router: "Router",
  Shell: "Shell",
  ShowerHead: "Shower Head",
  SwatchBook: "Swatch Book",
  Usb: "USB",
  Vault: "Vault",
  Volleyball: "Volleyball",
  WashingMachine: "Washing Machine",
  Wrench: "Wrench",
  Bird: "Bird",
  Bone: "Bone",
  Bug: "Bug",
  BugOff: "Bug Off",
  BugPlay: "Bug Play",
  Cat: "Cat",
  Dog: "Dog",
  Egg: "Egg",
  Fish: "Fish",
  FishOff: "Fish Off",
  FishSymbol: "Fish Symbol",
  Origami: "Origami",
  PawPrint: "Paw Print",
  Rabbit: "Rabbit",
  Rat: "Rat",
  Snail: "Snail",
  Squirrel: "Squirrel",
  Turtle: "Turtle",
  Worm: "Worm",
  Archive: "Archive",
  ArchiveRestore: "Archive Restore",
  ArchiveX: "Archive X",
  Container: "Container",
  Inbox: "Inbox",
  Mail: "Mail",
  MailCheck: "Mail Check",
  MailMinus: "Mail Minus",
  MailOpen: "Mail Open",
  MailPlus: "Mail Plus",
  MailQuestion: "Mail Question",
  MailSearch: "Mail Search",
  MailWarning: "Mail Warning",
  MailX: "Mail X",
  Mailbox: "Mailbox",
  Mails: "Mails",
  Paperclip: "Paperclip",
  Trash: "Trash",
  Trash2: "Trash 2",
  Copy: "Copy",
  Check: "Check",
};
